### ISSUE TITLE
未检测到原神窗口

### ISSUE THREAD

**Issue by huizichin** [YuehaiTeam/frostflake#1]
![image](https://user-images.githubusercontent.com/16850884/171996865-f1c67ff7-d186-4778-be82-c1d96d07643b.png)
![image](https://user-images.githubusercontent.com/16850884/171996867-93321a7c-9eb3-49cb-ba0e-57ba64d6c8e3.png)
国际服

**Comment by xytoki** [comment]
https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/issues
这个问题需要给cvautotrack提，我这边没法修复

**Comment by huizichin** [comment]
> 试了试私人服务器，改了点驱动名字去YuanShen.exe就能了。 ![image](https://user-images.githubusercontent.com/16850884/172019584-b98d5246-2350-47ff-94ac-14cc38998664.png) 看来是不支持国际服务器 ![image](https://user-images.githubusercontent.com/16850884/172019620-b5b74360-9a0f-462f-a10b-d0659cda76ee.png) 因为国际服务器是GenshinImpact.exe不是YuanShen.exe。有什么办法吗？ 把名字改掉只能在私人服务器实现，因为在正式服把驱动名字改掉会出现障碍 ![image](https://user-images.githubusercontent.com/16850884/172019832-430158ab-32bd-4d60-91bf-e49b321bfce6.png)
https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/issues/22#issuecomment-1146658959

**Comment by xytoki** [comment]
昨天推送了cvautotrack那边一个优化分辨率支持的patch，看看现在会不会好点？

**Comment by huizichin** [comment]
额，这怎么好像更严重了啊。1280x720都不能运行了
还是Code = 6

**Comment by xytoki** [comment]
麻了，但是他跟我说这个patch是优化多分辨率支持的才对，还是去他那边问问吧，目前推送的是他repo最新的release版本。
