### ISSUE TITLE
添加说明

### ISSUE THREAD

**Issue by Bilx-ZL** [YuehaiTeam/frostflake#2]
您应该在应用中添加说明，运行一次后会自动安装到"C:\Program Files\cocogoat-control"。今天属实给我整懵了

**Comment by xytoki** [comment]
十分抱歉，插件最早是绿色版运行，但每次都有大量用户反馈每次都找出来运行太过麻烦，并希望网页端能一键拉起插件，于是就改成了自动释放机制。插件可以在控制面板-添加删除程序里完全卸载，不会有任何残留。后续首次安装时会增加可选绿色版运行的选项。另，在绿色版运行模式下，当需要使用外部组件如yas、cvautotrack时，程序会将这些文件下载到exe同目录。

**Comment by xytoki** [comment]
或者可能会在下载页提供安装版和绿色版两个版本。

**Comment by xytoki** [comment]
https://github.com/YuehaiTeam/cocogoat/commit/4244e4dc6d352ec7c2740055252d76565de6d509

现在在下载页面做了提示，不自动安装的绿色版会在后面更新

**Comment by Bilx-ZL** [comment]
> [YuehaiTeam/cocogoat@4244e4d](https://github.com/YuehaiTeam/cocogoat/commit/4244e4dc6d352ec7c2740055252d76565de6d509)
> 
> 现在在下载页面做了提示，不自动安装的绿色版会在后面更新

不用更新绿色版，现在确实很方便。下载位置说明一下就可以了。
——
 主要是我不知道新的插件有此行为，所以产生了一系列奇怪的现象。因为用了一段时间椰羊，觉得挺好用的。今天看到插件更新，于是删掉了旧的exe。随后我就发现新的exe居然能在运行时被删掉，删掉后仍然能被浏览器拉起，很是疑惑。

**Comment by xytoki** [comment]
做安装主要是因为Program Files的特性（非管理员不可写）。因为目前的自动拉起是会自动管理员权限运行的，放在非管理员不可写的文件夹可以防止出现被恶意替换文件用来提权的情况，算是在方便和安全性之间做的一个权衡。

那Issue我先关闭，后面是计划把exe改名成带portable就不会自动安装。
